language: node_js
node_js:
- '0.11'
- '0.10'
env: SOCKETIO_SERVER=https://boundless-snake.herokuapp.com/
deploy:
  - provider: heroku
    app: boundless-snake
    on:
      repo: overflowgames/snake
      branch: master
      node: '0.10'
    api_key:
      secure: LNZJyVLHlECBaZB6TUOmFwHMfFeYLseU1EYOcjhF1ZZChTlW5dtEOor+5k3xgZpZ6ORNjdQ2xJ8kXTBFF2V8HZx4KzkONQFpt15sXOTy1bay37++S95Z1qHPk1r/hKdNRvyBLgb5FAHxJ6yXtL1zZlrVLLF1AuEvR1cqW/pKymY=
    skip_cleanup: true
  - provider: divshot
    skip_cleanup: true
    on:
      repo: overflowgames/snake
      branch: master
      node: '0.10'
    api_key:
      secure: SHxmEuhY/kev3RbwhJjAu+N/ImIkvzH5NBbw5lVaOnmbS4PLPrinzN3OiCQ3CwOCLOrbia8LL/glDI/kNK+VNTAD9yEE4S5zw19u2dI35KzJcL0GL0/f4EqBSIjDbDhj43/OfE8/Tp0DCfkZBvcMbN8keodv7kFG7P0TsVrTvsA=
